### ISSUE TITLE
error running drogon install (docker needs sudo permissions)

### ISSUE THREAD

**Issue by FidelVe** [icon-community/drogon#31]
## ISSUE: 

was able to run the following command without issue:
```
npm install -g @icon-community/drogon
```

After that when running `drogon install` I get the following error:
![Screenshot from 2023-03-28 18-20-43](https://user-images.githubusercontent.com/43641727/228527667-d254cd83-64e7-4bf9-abfe-d3e9c20293cd.png)

The issue is due to docker needed to be run with sudo in this machine, but when I run `sudo drogon install` the following error is raised
![Screenshot from 2023-03-28 18-23-08](https://user-images.githubusercontent.com/43641727/228527463-524b8318-1ea9-4400-816f-c00d450b6622.png)

## SOLUTION:

To fix this issue follow the instructions in the following link to be able to run docker without sudo
https://docs.docker.com/engine/install/linux-postinstall/

**Comment by han-so1omon** [comment]
@r3dsm0k3 Can this line be added to the docs in the `install` page?

**Comment by ant4g0nist** [comment]
This is now added to https://drogon.io/faq. Thank you @FidelVe for the raising the issue and providing solution.🙏
